### ISSUE TITLE
KeyError while executing PhenoTagger_training.py with latest hpo.obo

### ISSUE THREAD

**Issue by VivekTodur** [ncbi-nlp/PhenoTagger#10]
Hi, 

was just trying to rebuild the model using  the latest hpo.obo, was following the steps as mentioned in the readme. Program is crashing while executing the following,

**time python ../src/PhenoTagger_training.py -t ./distant_train_data/distant_train.conll -d ../data/corpus/GSC/GSCplus_dev_gold.tsv -m biobert -o ./models/**

Traceback (most recent call last):
  File "../src/PhenoTagger_training.py", line 185, in <module>
    BERT_training(trainfiles,vocabfiles,modelfile)
  File "../src/PhenoTagger_training.py", line 106, in BERT_training
    train_x,train_y=bert_model.rep.load_data(train_set,train_label,word_max_len=bert_model.maxlen)
  File "/home/PhenoTagger/src/nn_represent.py", line 247, in load_data
    y_list=self.generate_label_list(labels)
  File "/home/PhenoTagger/src/nn_represent.py", line 227, in generate_label_list
    temp_label[self.label_2_index[label]]=1
KeyError: 'HP:0034011'

**Comment by lingluodlut** [comment]
Hi, 
This error seem that you used old HPO dict files to retrain a model. Did you use the Build_dict.py file to generate the new dict files? You can see that the default dict files are load on lines 157-159, 172 in PhenoTagger_training.py file. Please check the loaded dict files are the new dict files.  If your new dict folder name is not 'dict' (default), you could renamed the folder  to 'dict', or change the lines in the script to load the new dict files.
BTW, our Web API for PhenoTagger has updated using the latest hpo.obo, you could also try it.
