### ISSUE TITLE
Python and dependencies update

### ISSUE THREAD

**Issue by azankl** [ncbi-nlp/PhenoTagger#13]
I have an Apple M1 MacBook Pro, which cannot natively run Python 3.7. The lowest supported version is 3.9.1. However, TensorFlow 2.3 will not work with Python 3.9 (and possibly some other dependencies neither). Could you update the Python and dependencies requirements to higher versions if possible?

**Comment by lingluodlut** [comment]
Hi Andreas, I am on vacation now, and I will update the versions later.

**Comment by lingluodlut** [comment]
Please see the PT1.2 https://github.com/DUTIR-BioNLP/PhenoTagger-Updates 
It can run with Python 3.10
