### ISSUE TITLE
Phenotagger API not working?

### ISSUE THREAD

**Issue by azankl** [ncbi-nlp/PhenoTagger#14]
I submitted the 'input' example to the Phenotagger API with:
`python SubmitText_request.py ../example/input Phenotype SessionNumber.txt`
but when I tried to retrieve the results  the next day with:
`python SubmitText_retrieve.py ../example/input SessionNumber.txt MyOutput`
I got the message: 
`8217-4755-8358-2994 : Result is not ready. please wait.`
Am I doing something wrong? It surely cannot take that long...

**Comment by lingluodlut** [comment]
The original API deponds on NIH's service. But now I have left NIH. So I am not sure if the API can work.
