### ISSUE TITLE
getting different offset when running Phenotagger example file

### ISSUE THREAD

**Issue by azankl** [ncbi-nlp/PhenoTagger#15]
I ran `PhenoTagger_tagging.py` on the `example/input/ex.BioC.XML` file. The output is similar to the `example/output/ex.BioC.XML` file, but the offset of the annotations is shifted by 114 characters, see screenshot below. Why is that happening?
<img width="1036" alt="Screenshot 2023-09-01 at 4 55 35 pm" src="https://github.com/ncbi-nlp/PhenoTagger/assets/4812335/8eb5440f-4ea3-4510-8072-9edda143b3e6">

**Comment by lingluodlut** [comment]
The original output ignored the previous text. For example, the extracted concept "schizophrenia" 's offset is 344, it is the offset of the current sentence. In fact, current sentence's begin offset is 114, so its exact offset in the documment should be 344+114=458. The new output fixs the bug. Please ignore the original output example. I will update it.
