### ISSUE TITLE
the format of corpus

### ISSUE THREAD

**Issue by ShujieLi-Vera** [ncbi-nlp/PhenoTagger#3]
hello!
I see you say that the input needs to be in BioC or PubTator format, but the corpus you give is not in such format.
I know the Corpus is standard annotation.
Could you please provide the datasets with correct input format of GSC+ and JAX, such as Pubtator format?
Thank you very much!

**Comment by lingluodlut** [comment]
I have uploaded the PubTator_input_format.zip file. It includes GSC and JAX input files in the PubTator format. You could download it.
