### ISSUE TITLE
Error: running tagger on examples

### ISSUE THREAD

**Issue by Maddocent** [ncbi-nlp/PhenoTagger#4]
When running the example code (command - in the Terminal from the ./src' folder: `python PhenoTagger_tagging.py -i ../example/input/ -o ../example/output/` in the README I am running into this ERROR:

`File "PhenoTagger_tagging.py", line 119     print("Processing:{0}%".format(round(i * 100 / N)), end="/r")`

I looked at the python src file, but with limited knowledge of the python syntax, I have not been able to fix the error myself. 

I unzipped the models into a folders called 'models' in the root of the cloned repo. Also, I have installed all necessary dependencies. 

Any pointers on how to resilve this issue would be very much appreciated.

Kind regards

**Comment by lingluodlut** [comment]
Could you please provide the completed error information? Line 119 only prints the processing progress.

**Comment by Maddocent** [comment]
I am sorry for the omission. The full error reads:

`File "PhenoTagger_tagging.py", line 119
    print("Processing:{0}%".format(round(i * 100 / N)), end="\r")
                                                           ^
SyntaxError: invalid syntax`

Hope this helps

**Comment by Maddocent** [comment]
for sake of completion: A screenshot of the error in the Terminal:

<img width="624" alt="afbeelding" src="https://user-images.githubusercontent.com/12751032/132937662-0dd49740-a183-4b48-8979-87fcfcc3e8eb.png">

**Comment by lingluodlut** [comment]
I think this issue may be caused by the version of Python. Which version is your Python? Our codes are tested in Python3.7.

**Comment by Maddocent** [comment]
Thank you very much for the pointer. I changed the python version in the conda environment. The error is gone, but replaced by a different error that most likely involves incomatibility with the Apple Silicon M1 chip in my MacBook. The error I am now getting is `illegal hardware instruction`, when running the command: `python PhenoTagger_tagging.py -i ../input/ -o ../output/ `. I will see if there is something known about this, before posting a new issue here.
