### ISSUE TITLE
Get HPO tag by PubTator API.

### ISSUE THREAD

**Issue by YaoXinZhi** [ncbi-nlp/PhenoTagger#9]
I saw in the introduction of Phenotagger that it is possible to get HPO annotations by modifying the Bioconcept to Phenotype in PubTator API, so I modified several examples provided in
[PubTator API](https://www.ncbi.nlm.nih.gov/research/pubtator/api.html)
, for example:
`https://www.ncbi.nlm.nih.gov/research/pubtator-api/publications/export/pubtator?pmids=28483577&concepts=phenotype
`
, but did not get any HPO annotations, such as the asthma in the text.

Is there any other way to modify this API url?

**Comment by YaoXinZhi** [comment]
And I used the SubmitText_request.py and SubmitText_retrieve.py scripts and did not get any results, although it shows
 "Thanks for your submission. The session number is: 7781-7181-3052-9041"
And 
"7781-7181-3052-9041: Result is retrieved."

**Comment by YaoXinZhi** [comment]
Hi ling luo
thank you for your help. I believe that the updated PhenoTagger will better serve the development of the BioNLP community.

**Comment by lingluodlut** [comment]
Hi XinZhi,

I would like to know if you are using our PhenoTagger API? Recently, I received feedback from my colleague that someone is using our API and the input format is in BioC-JSON. But our API can’t access it (The API accepts PubAnnotation-JSON). The failed format caused the input 1000 articles merged in one huge sentence.  If yes, could you please use PubTator or BioC-XML formats instead BioC-JSON format, and slow down the process (i.e., each input file includes fewer articles). Thanks.
